server:
    port: 9999
spring:
    application:
        name: WebMovieApplication
    datasource:
        password: duc1531
        url: jdbc:mysql://localhost:3306/MovieApplication_mvn?createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                show_sql: true
                format_sql: true
    servlet:
        multipart:
            max-file-size: 15MB
            max-request-size: 25MB

firebase-bucket: "webmovieapplication-d3308.appspot.com"

